version: "3.8"

volumes:
  keycloak:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    ports:
      - 8180:8180
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak:/opt/keycloak/data/
    restart: always
    command:
      - "start-dev --http-port 8180"
  opa:
    image: openpolicyagent/opa:0.50.0-envoy-1
    platform: linux/amd64
    ports:
      - "8181:8181"
      - "8282:8282"
      - "9191:9191"
    volumes:
      - ./policies:/policies
    command:
      - "run"
      - "--server"
      - "--log-format=json"
      - "--set=decision_logs.console=true"
      - "--diagnostic-addr=0.0.0.0:8282"
      - "--set=plugin.envoy_ext_authz_grpc.addr=:9191"
      - "--set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.allow"
      - "/policies"